export const TRAINING_TYPES = ["客户情景陪练", "商机推进教练"];
export const OPPORTUNITY_MODE = "商机推进教练";

export const opportunityStages = [
  {
    name: "了解商机",
    note: "拿到有效线索，建立直接沟通入口，并约到首次拜访。",
    flow: [
      ["线索获取", "找到潜在客户来源，判断是否值得进入跟进。"],
      ["加微信", "建立直接沟通入口，方便后续资料和拜访安排。"],
      ["约拜访", "把线上线索推进到一次明确的客户接触。"],
    ],
  },
  {
    name: "确认商机",
    note: "确认客户真实需求，尽快取得样品，并推动再次拜访。",
    flow: [
      ["首次拜访", "确认客户需求、使用场景和关键联系人。"],
      ["取得样品", "拿到样品或工艺条件，为后续方案论证做准备。"],
      ["未拿到样品", "识别阻碍原因，判断客户意愿或内部限制。"],
      ["再次拜访", "针对未完成事项继续推进客户接触。"],
    ],
  },
  {
    name: "方案论证",
    note: "围绕打样、报告、送样和试样反馈推进方案验证。",
    flow: [
      ["内部打样", "根据样品和需求组织内部方案验证。"],
      ["出具报告", "形成客户可判断的检测、对比或方案依据。"],
      ["送样", "把方案推进到客户试样环节。"],
      ["客户试样", "跟进试样反馈，确认通过或未通过原因。"],
      ["试样通过", "把技术验证转入商务条件确认。"],
      ["试样未通过", "复盘原因，决定是否重新打样。"],
      ["分析原因重新打样", "针对问题调整方案并再次验证。"],
    ],
  },
  {
    name: "商务谈判",
    note: "处理报价、价格异议、账期和交付条件。",
    flow: [
      ["报价", "给出报价并解释价值、成本和交付边界。"],
      ["商务谈判", "围绕价格、账期、交付和责任条件达成一致。"],
    ],
  },
  {
    name: "销售成交",
    note: "推动合同签订，并保障订单交付边界清晰。",
    flow: [
      ["签订合同", "确认合同条款、价格、交付和责任边界。"],
      ["订单交付", "推动订单按时间、质量和服务要求交付。"],
    ],
  },
  {
    name: "回款",
    note: "跟进回款事项，稳定服务体验，并推动客户复购。",
    flow: [
      ["跟进回款", "根据账期和约定节奏推进回款。"],
      ["服务", "稳定客户服务体验，减少回款和复购阻力。"],
      ["复购", "在服务稳定后推动下一轮需求确认。"],
    ],
  },
];

export const stageTrainingGoals = {
  了解商机: [
    { id: "lead", name: "线索判断", desc: "判断线索是否值得进入跟进，并明确客户来源。" },
    { id: "visit", name: "首次触达", desc: "建立直接沟通入口，完成微信或电话连接。" },
    { id: "stalled", name: "约到拜访", desc: "把线上线索推进到一次明确的客户接触。" },
  ],
  确认商机: [
    { id: "stalled", name: "需求澄清", desc: "确认客户真实需求、使用场景和判断标准。" },
    { id: "sample", name: "取得样品", desc: "推动客户提供样品或工艺条件。" },
    { id: "stakeholder", name: "关键人确认", desc: "找到采购、技术或老板中的关键影响人。" },
    { id: "visit", name: "再次拜访", desc: "针对未完成事项推动下一次客户接触。" },
  ],
  方案论证: [
    { id: "technical", name: "技术交涉", desc: "解释工艺、产品方案或测试条件。" },
    { id: "trial", name: "试样推进", desc: "推动客户完成试样并给出反馈。" },
    { id: "report", name: "报告讲解", desc: "把检测、对比或方案依据讲清楚。" },
    { id: "stalled", name: "未通过复盘", desc: "试样未通过时确认原因并推动重新打样。" },
  ],
  商务谈判: [
    { id: "price", name: "价格异议", desc: "客户认为报价高，不愿替换现有供应商。" },
    { id: "contract", name: "条件谈判", desc: "围绕价格、账期、交付和责任条件收口。" },
    { id: "report", name: "报价解释", desc: "解释报价背后的稳定性、服务和交付价值。" },
    { id: "stalled", name: "成交推进", desc: "客户犹豫时锁定下一步动作和时间点。" },
  ],
  销售成交: [
    { id: "contract", name: "合同签订", desc: "推动合同条款、价格和交付边界确认。" },
    { id: "delivery", name: "订单交付", desc: "确认订单交付时间、质量和服务要求。" },
    { id: "stakeholder", name: "责任边界", desc: "明确客户与内部的责任人和交付边界。" },
  ],
  回款: [
    { id: "payment", name: "回款交涉", desc: "客户拖延付款或账期压力大。" },
    { id: "service", name: "服务稳定", desc: "用服务体验降低回款和复购阻力。" },
    { id: "retention", name: "老客维护", desc: "客户订单减少或出现断单风险。" },
    { id: "stalled", name: "复购推进", desc: "在服务稳定后推动下一轮需求确认。" },
  ],
};

export const trainingGoals = stageTrainingGoals["商务谈判"];

export const customerDifficultyOptions = ["标准", "刁钻", "高压"];
export const customerPersonalityOptions = ["谨慎型", "压价型", "专业型", "敷衍型"];
export const customerConcernOptions = ["价格", "交期", "品质", "售后"];

export const trainingTemplates = [
  {
    id: "price-objection",
    title: "价格异议",
    subtitle: "客户认为报价偏高",
    training_type: "客户情景陪练",
    stage: "商务谈判",
    goal: "价格异议",
    customer_type: "新客户，价格敏感",
    product_name: "活性染料固色盐",
    product_need: "稳定交付，但希望先压低采购成本",
    background: "客户正在比较多家供应商，认为当前报价偏高，希望先降价再继续谈。",
    customer_difficulty: "高压",
    customer_personality: "压价型",
    customer_concern: "价格",
  },
  {
    id: "delivery-risk",
    title: "交期确认",
    subtitle: "客户担心交付延误",
    training_type: "客户情景陪练",
    stage: "方案论证",
    goal: "交期保障",
    customer_type: "渠道客户，关注交期",
    product_name: "活性染料固色盐",
    product_need: "按期交付，避免影响下游排产",
    background: "客户担心旺季交付不稳定，要求说明排产、备货和异常处理方案。",
    customer_difficulty: "刁钻",
    customer_personality: "谨慎型",
    customer_concern: "交期",
  },
  {
    id: "quality-proof",
    title: "品质质疑",
    subtitle: "客户要求稳定性依据",
    training_type: "客户情景陪练",
    stage: "方案论证",
    goal: "技术质疑",
    customer_type: "技术型客户，关注工艺",
    product_name: "活性染料固色盐",
    product_need: "确认稳定性、测试条件和返工风险",
    background: "客户技术负责人要求看到测试条件、稳定性数据和异常处理边界。",
    customer_difficulty: "刁钻",
    customer_personality: "专业型",
    customer_concern: "品质",
  },
  {
    id: "stalled-opportunity",
    title: "商机停滞",
    subtitle: "资料发出后客户没有推进",
    training_type: OPPORTUNITY_MODE,
    stage: "确认商机",
    goal: "商机停滞",
    customer_type: "新客户，内部决策不清晰",
    product_name: "活性染料固色盐",
    product_need: "确认关键人和下一步测试条件",
    background: "客户收资料后没有明确反馈，需要重新推动关键人参与和下一步动作。",
    last_contact: "客户说先内部看看资料，之后一直没有明确反馈。",
    decision_blocker: "关键人未参与",
    next_milestone: "约到关键人会议",
    stakeholder: "采购已沟通，技术负责人还未参与",
    customer_difficulty: "标准",
    customer_personality: "敷衍型",
    customer_concern: "售后",
  },
  {
    id: "payment-followup",
    title: "回款推进",
    subtitle: "客户拖延付款节点",
    training_type: "客户情景陪练",
    stage: "回款",
    goal: "回款交涉",
    customer_type: "老客户，流程较慢",
    product_name: "活性染料固色盐",
    product_need: "确认付款流程、责任人和预计时间",
    background: "客户已经确认订单和交付，但付款流程迟迟没有明确时间。",
    customer_difficulty: "标准",
    customer_personality: "谨慎型",
    customer_concern: "售后",
  },
  {
    id: "payment-quality-objection",
    title: "回款异议",
    subtitle: "客户以质量问题为由压款",
    training_type: "客户情景陪练",
    stage: "回款",
    goal: "回款交涉",
    customer_type: "老客户，订单减少",
    product_name: "湿摩擦牢度提升剂",
    product_need: "先解决质量问题再付款",
    background: "客户反馈某批次湿摩擦牢度不达标，以此为由暂缓付款；该批次出货前有质检报告和留样，问题可能出在工艺使用端。",
    customer_difficulty: "刁钻",
    customer_personality: "专业型",
    customer_concern: "品质",
  },
  {
    id: "payment-extension",
    title: "账期协商",
    subtitle: "客户资金紧张要求延期",
    training_type: "客户情景陪练",
    stage: "回款",
    goal: "回款交涉",
    customer_type: "老客户，流程较慢",
    product_name: "活性染料固色盐",
    product_need: "本批先付部分、尾款延后两个月",
    background: "客户下游回款慢，现金流紧张，提出本批先付50%、尾款延后60天，希望维持长期合作。",
    customer_difficulty: "高压",
    customer_personality: "压价型",
    customer_concern: "售后",
  },
  {
    id: "cold-call-phone",
    title: "电话陌拜",
    subtitle: "首次电话接触染厂采购",
    training_type: "客户情景陪练",
    stage: "了解商机",
    goal: "首次触达",
    customer_type: "新客户，价格敏感",
    product_name: "亲水柔软硅油",
    product_need: "破冰并约到微信",
    background: "通过行业名录拿到某针织染厂采购的电话，这是第一次电话联系，目标是在30秒内破冰、了解当前供应情况并约到微信。",
    customer_difficulty: "高压",
    customer_personality: "敷衍型",
    customer_concern: "价格",
  },
  {
    id: "new-mill-visit",
    title: "新厂陌拜",
    subtitle: "首次拜访新投产染厂",
    training_type: OPPORTUNITY_MODE,
    stage: "了解商机",
    goal: "约到拜访",
    customer_type: "新客户，内部决策不清晰",
    product_name: "湿摩擦牢度提升剂",
    product_need: "首次拜访建立印象并约到关键人",
    background: "目标客户是本地新投产的针织染厂，供应商尚未定型，同行已开始接触；通过行业朋友转介绍获得联系入口。",
    last_contact: "通过转介绍获得联系方式，尚未正式接触。",
    decision_blocker: "关键人未参与",
    next_milestone: "约到首次拜访",
    stakeholder: "暂无直接联系人，采购与技术的决策关系未知",
    customer_difficulty: "标准",
    customer_personality: "敷衍型",
    customer_concern: "交期",
  },
];

export const standardReplies = {
  线索判断: "我想先确认一下贵司当前是否真的有替换或新增供应的需求。方便的话，我们先对齐使用场景、当前供应痛点和预计推进时间，再判断是否值得进入下一步。",
  首次触达: "您好，我这边主要想先了解贵司当前用料和供应稳定性情况。如果合适，我可以先发一份简要资料，后续再约一个更具体的沟通时间。",
  约到拜访: "为了不只停留在资料沟通，我建议约一次简短拜访，把使用场景、样品条件和关键关注点一次性确认清楚。",
  需求澄清: "我先不急着推荐方案，想确认三个问题：当前使用场景是什么、最在意的指标是什么、这次评估由谁来判断是否通过。",
  取得样品: "如果要判断方案是否适配，最好先拿到样品或工艺条件。您看我们是否可以先确认样品规格和测试标准？",
  关键人确认: "这件事后续会涉及采购、技术和使用端判断。为了避免来回传话，我们能否把关键评估人一起拉进下一次沟通？",
  再次拜访: "上次沟通后还有几个点没有收口，我建议再约一次，把样品、测试条件和下一步责任人明确下来。",
  价格异议: "我理解您对价格敏感。我们先不急着谈降价，我想先和您确认三件事：稳定性损耗、交付周期风险，以及这次测试通过后能否进入下一步技术确认。",
  商机停滞: "我担心这个项目现在卡在下一步责任人不清晰。我们能不能先约一次 20 分钟沟通，把技术、采购和测试条件一次性确认下来？",
  技术交涉: "这个问题我建议用测试条件来对齐。您方便把当前工艺参数和评判标准发我吗？我会按同一标准给出对比说明和样品验证建议。",
  试样推进: "现在关键不是继续讨论概念，而是把试样条件、评判标准和反馈时间定下来。您看这周能否先安排一次试样确认？",
  报告讲解: "这份报告我想重点和您对齐三点：测试条件是否一致、关键指标差异在哪里、这些差异会怎样影响稳定性和返修成本。",
  未通过复盘: "试样没有通过没关系，我们先把原因拆清楚：是工艺条件、样品匹配、指标要求，还是操作过程影响。确认后再决定是否重新打样。",
  条件谈判: "价格可以谈，但我希望和交付周期、账期、质量责任一起确认，避免只压单价却把后续风险放大。",
  报价解释: "这次报价里不只是单价，还包含稳定性、交付响应和后续服务成本。我们可以先看总使用成本，再判断是否还有调整空间。",
  成交推进: "目前信息已经比较完整，我建议把下一步收敛成一个明确动作：确认关键人、确认条件，或者约定合同节点。",
  合同签订: "我们可以先把合同里最容易反复的价格、交付、质量和责任边界确认掉，避免后面影响订单执行。",
  订单交付: "订单交付我建议先确认时间、质量标准和异常响应方式，这样双方后续执行会更稳。",
  责任边界: "为了避免后续扯皮，我们先明确双方责任人、交付节点、验收标准和异常处理方式。",
  回款交涉: "我理解贵司账期压力，不过这笔款项已经影响后续服务安排。我们能否今天先确认付款节点，如果需要拆分，也请明确金额和日期。",
  服务稳定: "回款和复购都和服务体验有关。我想先确认最近服务里最影响贵司判断的问题，再一起定一个恢复稳定的动作。",
  老客维护: "我想先复盘最近订单减少的真实原因，是价格、库存、交付还是服务体验。确认原因后，我们再一起定一个恢复采购的动作。",
  复购推进: "如果前期服务和交付没有问题，我们可以一起看下一轮需求计划，先确认时间、规格和可能的备货安排。",
};

export const defaultForm = {
  training_type: "客户情景陪练",
  stage: "商务谈判",
  goal: "价格异议",
  owner_name: "陈宇",
  customer_name: "锦兴印染",
  customer_type: "老客户，订单减少",
  product_name: "活性染料固色盐",
  product_need: "稳定性和交付保障",
  background: "客户是佛山区 OEM 配套客户，近期订单下滑，对活性染料固色盐价格敏感，同时担心稳定性和交付周期。采购要求先降价，技术负责人还没有参与。",
  last_contact: "客户收了报价和测试资料，但没有确认下一次技术沟通时间。",
  decision_blocker: "关键人未参与",
  next_milestone: "约到关键人会议",
  stakeholder: "采购已参与，技术负责人未参与",
  customer_difficulty: "标准",
  customer_personality: "谨慎型",
  customer_concern: "价格",
  template_id: "",
};
